// Textes de l'interface, centralisés (français). Traduisible en un seul endroit.

export const T = {
  // Manette — accueil
  titre: 'Bowling',
  manette: 'Manette',
  codeSalle: 'Code de la salle',
  prenom: 'Ton prénom',
  couleur: 'Couleur',
  main: 'Main',
  droite: 'Droite',
  gauche: 'Gauche',
  rejoindre: 'Activer les capteurs et rejoindre',
  noteCapteurs: 'Les capteurs de mouvement ne servent que pendant la partie ; les données restent sur le Wi-Fi local.',
  codeInvalide: 'Code de salle : 5 lettres ou chiffres.',
  nomRequis: 'Indique ton prénom.',
  capteursRefuses: 'Accès aux capteurs refusé. Recharge la page pour redemander.',
  capteursIndisponibles: 'Capteurs de mouvement indisponibles sur cet appareil (la manette fonctionnera en mode Glisser ou boutons seulement).',
  capteursHttps: 'Les capteurs de mouvement exigent une page en HTTPS.',
  refus: 'Connexion refusée par l’écran.',
  sallePleine: 'Salle pleine (4 manettes maximum).',
  versionProtocole: 'Version de la manette différente de celle de l’écran : recharge les deux pages.',

  // Manette — états du lien
  connexion: 'Connexion…',
  connecte: 'Connecté',
  reconnexion: 'Reconnexion…',
  salleIntrouvable: 'Salle introuvable — l’écran est-il ouvert ?',

  // Manette — jeu
  attendsTonTour: 'Attends ton tour',
  passer: 'Passer ▶',
  passerAide: 'Touche pour passer la cinématique',
  salon: 'Salon',
  salonAide: 'En attente du lancement de la partie',
  commencer: 'Commencer ▶',
  commencerAide: 'Touche pour lancer la partie',
  partieTerminee: 'Partie terminée',
  partieTermineeAide: 'Regarde l’écran pour le classement',
  auTourDe: 'Au tour de',
  aToi: 'À toi !',
  passeTelephone: 'Passe le téléphone à',
  pasTonTour: 'Ce n’est pas ton tour',
  lancer: 'LANCER',
  balance: 'Balance…',
  glisse: 'Glisse…',
  consigneRelacher: 'Pose le pouce, balance, lève le pouce',
  consigneAutomatique: 'Pose le pouce, balance, lève quand tu veux',
  consigneGlisser: 'Glisse le doigt vers le haut',
  lancerEnvoye: 'Lancer envoyé',
  lancerAnnule: 'Lancer annulé',
  position: 'Position',
  angle: 'Angle',
  quitter: 'Quitter',
  capteurs: 'Capteurs',
  ecranAllume: 'Écran maintenu allumé',
  ecranNonMaintenu: 'Écran non maintenu : désactive le verrouillage automatique',

  raisons: {
    tropCourt: 'geste trop court',
    tropFaible: 'geste trop faible',
    pasTonTour: 'ce n’est pas ton tour',
  },
  phases: {
    normal: 'normal',
    lob: 'lobé',
    arriere: 'en arrière',
  },
  modes: {
    relacher: 'Relâcher',
    automatique: 'Automatique',
    glisser: 'Glisser',
  },
};
